#!/bin/bash

module load singularity 2> /dev/null

# create brainmask
#singularity exec -e docker://brainlife/vistasoftregistration ./brainmask.sh
singularity exec -e docker://brainlife/fsl:5.0 ./brainmask.sh

# registration
singularity exec -e docker://brainlife/mcr:neurodebian1604-r2017a ./compiled/main

# clean up
#singularity exec -e docker://brainlife/vistasoftregistration /app/clean.sh
mv data_acpc.nii.gz dwi.nii.gz;
mv bvecs_rot dwi.bvecs;
bvecs=`jq -r '.bvecs' config.json`;
mv ${bvals} dwi.bvals;
rm -rf *nodif*;

echo "DWI Registration Pipeline Complete"

if [ ! -s dwi.nii.gz ];
then
	echo "output missing"
	exit 1
fi
